In [127]:
import pandas as pd

In [128]:
df_nyclu = pd.read_csv('CCRB_database_raw.csv')
print(df_nyclu.shape)
df_nyclu.head()

(323911, 14)

,AsOfDate,Unique Id,First Name,Last Name,Rank,Command,ShieldNo,Complaint Id,Incident Date,FADO Type,Allegation,Board Disposition,NYPDDisposition,PenaltyDesc
0,7/14/2020,43921,Richard,Aalbue,POM,H BKLYN,3619.0,6290465.0,NaN,Force,Force,Unsubstantiated,NaN,NaN
1,7/14/2020,52580,Walter,Aanonsen,LT,MOUNTED,0.0,8300607.0,NaN,Force,Force,Complainant Unavailable,NaN,NaN
2,7/14/2020,52580,Walter,Aanonsen,LT,MOUNTED,0.0,8800504.0,2/15/1988,Force,Beat,Unsubstantiated,NaN,NaN
3,7/14/2020,52580,Walter,Aanonsen,LT,MOUNTED,0.0,9201176.0,4/2/1992,Abuse of Authority,Vehicle Searched,Unsubstantiated,NaN,NaN
4,7/14/2020,52580,Walter,Aanonsen,LT,MOUNTED,0.0,9201176.0,4/2/1992,Discourtesy,Nasty Words,Unsubstantiated,NaN,NaN

In [129]:
df_ccrb = pd.read_csv('From CCRB via ProPublica/CCRB-Complaint-Data_202007271729/allegations_202007271729.csv')

In [130]:
print(df_ccrb.shape)
df_ccrb.head()

(33358, 27)

,unique_mos_id,first_name,last_name,command_now,shield_no,complaint_id,month_received,year_received,month_closed,year_closed,...,mos_age_incident,complainant_ethnicity,complainant_gender,complainant_age_incident,fado_type,allegation,precinct,contact_reason,outcome_description,board_disposition
0,10004,Jonathan,Ruiz,078 PCT,8409,42835,7,2019,5,2020,...,32,Black,Female,38.0,Abuse of Authority,Failure to provide RTKA card,78.0,Report-domestic dispute,No arrest made or summons issued,Substantiated (Command Lvl Instructions)
1,10007,John,Sears,078 PCT,5952,24601,11,2011,8,2012,...,24,Black,Male,26.0,Discourtesy,Action,67.0,Moving violation,Moving violation summons issued,Substantiated (Charges)
2,10007,John,Sears,078 PCT,5952,24601,11,2011,8,2012,...,24,Black,Male,26.0,Offensive Language,Race,67.0,Moving violation,Moving violation summons issued,Substantiated (Charges)
3,10007,John,Sears,078 PCT,5952,26146,7,2012,9,2013,...,25,Black,Male,45.0,Abuse of Authority,Question,67.0,PD suspected C/V of violation/crime - street,No arrest made or summons issued,Substantiated (Charges)
4,10009,Noemi,Sierra,078 PCT,24058,40253,8,2018,2,2019,...,39,NaN,NaN,16.0,Force,Physical force,67.0,Report-dispute,Arrest - other violation/crime,Substantiated (Command Discipline A)

In [131]:
df_ccrb.columns

Index(['unique_mos_id', 'first_name', 'last_name', 'command_now', 'shield_no',
       'complaint_id', 'month_received', 'year_received', 'month_closed',
       'year_closed', 'command_at_incident', 'rank_abbrev_incident',
       'rank_abbrev_now', 'rank_now', 'rank_incident', 'mos_ethnicity',
       'mos_gender', 'mos_age_incident', 'complainant_ethnicity',
       'complainant_gender', 'complainant_age_incident', 'fado_type',
       'allegation', 'precinct', 'contact_reason', 'outcome_description',
       'board_disposition'],
      dtype='object')

In [132]:
# df_ccrb = df_ccrb[['unique_mos_id', 'first_name', 'last_name', 'rank_now', 'command_now',
#                    'shield_no', 'complaint_id', 'fado_type', 'allegation', 'board_disposition'
#                     ]]

In [133]:
df_ccrb.rename({'unique_mos_id': 'Unique Id', 'first_name': 'First Name', 'last_name': 'Last Name',
                'rank_now': 'Rank', 'command_now': 'Command', 'shield_no': 'ShieldNo',
                'complaint_id': 'Complaint Id', 'fado_type': 'FADO Type', 
                'allegation': 'Allegation', 'board_disposition': 'Board Disposition'},
                axis=1, inplace=True)
df_ccrb.head()

,Unique Id,First Name,Last Name,Command,ShieldNo,Complaint Id,month_received,year_received,month_closed,year_closed,...,mos_age_incident,complainant_ethnicity,complainant_gender,complainant_age_incident,FADO Type,Allegation,precinct,contact_reason,outcome_description,Board Disposition
0,10004,Jonathan,Ruiz,078 PCT,8409,42835,7,2019,5,2020,...,32,Black,Female,38.0,Abuse of Authority,Failure to provide RTKA card,78.0,Report-domestic dispute,No arrest made or summons issued,Substantiated (Command Lvl Instructions)
1,10007,John,Sears,078 PCT,5952,24601,11,2011,8,2012,...,24,Black,Male,26.0,Discourtesy,Action,67.0,Moving violation,Moving violation summons issued,Substantiated (Charges)
2,10007,John,Sears,078 PCT,5952,24601,11,2011,8,2012,...,24,Black,Male,26.0,Offensive Language,Race,67.0,Moving violation,Moving violation summons issued,Substantiated (Charges)
3,10007,John,Sears,078 PCT,5952,26146,7,2012,9,2013,...,25,Black,Male,45.0,Abuse of Authority,Question,67.0,PD suspected C/V of violation/crime - street,No arrest made or summons issued,Substantiated (Charges)
4,10009,Noemi,Sierra,078 PCT,24058,40253,8,2018,2,2019,...,39,NaN,NaN,16.0,Force,Physical force,67.0,Report-dispute,Arrest - other violation/crime,Substantiated (Command Discipline A)

In [134]:
df_combined = pd.concat([df_nyclu, df_ccrb], axis=0)

/Users/michaeleby1/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

In [135]:
print(df_combined.shape)
df_combined.head()

(357269, 31)

,Allegation,AsOfDate,Board Disposition,Command,Complaint Id,FADO Type,First Name,Incident Date,Last Name,NYPDDisposition,...,mos_age_incident,mos_ethnicity,mos_gender,outcome_description,precinct,rank_abbrev_incident,rank_abbrev_now,rank_incident,year_closed,year_received
0,Force,7/14/2020,Unsubstantiated,H BKLYN,6290465.0,Force,Richard,NaN,Aalbue,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Force,7/14/2020,Complainant Unavailable,MOUNTED,8300607.0,Force,Walter,NaN,Aanonsen,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Beat,7/14/2020,Unsubstantiated,MOUNTED,8800504.0,Force,Walter,2/15/1988,Aanonsen,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Vehicle Searched,7/14/2020,Unsubstantiated,MOUNTED,9201176.0,Abuse of Authority,Walter,4/2/1992,Aanonsen,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Nasty Words,7/14/2020,Unsubstantiated,MOUNTED,9201176.0,Discourtesy,Walter,4/2/1992,Aanonsen,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [104]:
df_combined.columns

Index(['Allegation', 'AsOfDate', 'Board Disposition', 'Command',
       'Complaint Id', 'FADO Type', 'First Name', 'Incident Date', 'Last Name',
       'NYPDDisposition', 'PenaltyDesc', 'Rank', 'ShieldNo', 'Unique Id',
       'command_at_incident', 'complainant_age_incident',
       'complainant_ethnicity', 'complainant_gender', 'contact_reason',
       'month_closed', 'month_received', 'mos_age_incident', 'mos_ethnicity',
       'mos_gender', 'outcome_description', 'precinct', 'rank_abbrev_incident',
       'rank_abbrev_now', 'rank_incident', 'year_closed', 'year_received'],
      dtype='object')

In [105]:
df_personnel = pd.read_csv('New York, NY/From a source/NYPD Personnel Orders.csv', engine='python')

In [106]:
print(df_personnel.shape)
df_personnel.head()

(2095, 11)

,Source Image,Case,Rank,Name,Tax No.,Present Command,Command Pref�d Charges,Date of Charges,Date of Disposition,ProperSpecs,ProperPenalty
0,October-December-2013-155.png,2011-4889,ADMIN TEA,PETER MURILLO,331345,BX.TOW.PND.,IAB,9/13/2011,4/24/2013,1.Did Improperly Release A Towed Vehicle That ...,Forfeiture Of Five (5) Days Annual Leave.
1,April-June-2012-304.png,2010-3306,ADMIN. SSM,WILBUR JONES,335663,SSD,IAB,1/3/2011,1/31/2012,1. Improperly Issued A Command Discipline To A...,Forfeiture Of Five (5) Vacation Days.
2,July-September-2012-229.png,2011-5511,AGENCY ATT.,Evan Gluck,350518,LEGAL BUR.,IAB,1/19/2012,6/26/2012,1. Wrongfully Prepared Two (2) Criminal Court ...,Forfeiture Of Thirty (30) Vacation Days.
3,January-March-2012-3.png,2010-86576,AM,RICHARD SAUNDERS,345566,FLEET SERV. DIV.,FLEET SERV. DIV.,3/16/2010,9/15/2011,1. Engaged In A Physical Altercation With A Fa...,Forfeiture Of Thirty (30) Days Time On Suspens...
4,October-December-2013-154.png,2012-7397,ARCH.,Godswill Ogbonnaya,326144,BUILD. MAINT. SECT.,BUILD. MAINT. SECT.,6/4/2012,4/23/2013,1. Failed To Give Notice To The Department Tha...,See Penalty For Case #2010-1928.

In [107]:
df_personnel.rename({'Command Pref�d Charges': 'Investigating Agency'}, axis=1, inplace=True)

In [108]:
df_personnel[['First Name','Last Name']] = df_personnel['Name'].loc[df_personnel['Name'].str.split().str.len() == 2].str.split(expand=True)

In [109]:
df_personnel.drop('Name', axis=1, inplace=True)
df_personnel['First Name'] = df_personnel['First Name'].str.title()
df_personnel['Last Name'] = df_personnel['Last Name'].str.title()
df_personnel.head()

,Source Image,Case,Rank,Tax No.,Present Command,Investigating Agency,Date of Charges,Date of Disposition,ProperSpecs,ProperPenalty,First Name,Last Name
0,October-December-2013-155.png,2011-4889,ADMIN TEA,331345,BX.TOW.PND.,IAB,9/13/2011,4/24/2013,1.Did Improperly Release A Towed Vehicle That ...,Forfeiture Of Five (5) Days Annual Leave.,Peter,Murillo
1,April-June-2012-304.png,2010-3306,ADMIN. SSM,335663,SSD,IAB,1/3/2011,1/31/2012,1. Improperly Issued A Command Discipline To A...,Forfeiture Of Five (5) Vacation Days.,Wilbur,Jones
2,July-September-2012-229.png,2011-5511,AGENCY ATT.,350518,LEGAL BUR.,IAB,1/19/2012,6/26/2012,1. Wrongfully Prepared Two (2) Criminal Court ...,Forfeiture Of Thirty (30) Vacation Days.,Evan,Gluck
3,January-March-2012-3.png,2010-86576,AM,345566,FLEET SERV. DIV.,FLEET SERV. DIV.,3/16/2010,9/15/2011,1. Engaged In A Physical Altercation With A Fa...,Forfeiture Of Thirty (30) Days Time On Suspens...,Richard,Saunders
4,October-December-2013-154.png,2012-7397,ARCH.,326144,BUILD. MAINT. SECT.,BUILD. MAINT. SECT.,6/4/2012,4/23/2013,1. Failed To Give Notice To The Department Tha...,See Penalty For Case #2010-1928.,Godswill,Ogbonnaya

In [110]:
df_personnel.rename({'Present Command': 'Command'}, axis=1, inplace=True)

In [125]:
df_personnel.head()

,Source Image,Case,Rank,Tax No.,Command,Investigating Agency,Date of Charges,Date of Disposition,ProperSpecs,ProperPenalty,First Name,Last Name
0,October-December-2013-155.png,2011-4889,ADMIN TEA,331345,BX.TOW.PND.,IAB,9/13/2011,4/24/2013,1.Did Improperly Release A Towed Vehicle That ...,Forfeiture Of Five (5) Days Annual Leave.,Peter,Murillo
1,April-June-2012-304.png,2010-3306,ADMIN. SSM,335663,SSD,IAB,1/3/2011,1/31/2012,1. Improperly Issued A Command Discipline To A...,Forfeiture Of Five (5) Vacation Days.,Wilbur,Jones
2,July-September-2012-229.png,2011-5511,AGENCY ATT.,350518,LEGAL BUR.,IAB,1/19/2012,6/26/2012,1. Wrongfully Prepared Two (2) Criminal Court ...,Forfeiture Of Thirty (30) Vacation Days.,Evan,Gluck
3,January-March-2012-3.png,2010-86576,AM,345566,FLEET SERV. DIV.,FLEET SERV. DIV.,3/16/2010,9/15/2011,1. Engaged In A Physical Altercation With A Fa...,Forfeiture Of Thirty (30) Days Time On Suspens...,Richard,Saunders
4,October-December-2013-154.png,2012-7397,ARCH.,326144,BUILD. MAINT. SECT.,BUILD. MAINT. SECT.,6/4/2012,4/23/2013,1. Failed To Give Notice To The Department Tha...,See Penalty For Case #2010-1928.,Godswill,Ogbonnaya

In [126]:
df_combined

,Allegation,AsOfDate,Board Disposition,Case,Command,Complaint Id,Date of Charges,Date of Disposition,FADO Type,First Name,...,mos_age_incident,mos_ethnicity,mos_gender,outcome_description,precinct,rank_abbrev_incident,rank_abbrev_now,rank_incident,year_closed,year_received
0,Force,7/14/2020,Unsubstantiated,NaN,H BKLYN,6290465.0,NaN,NaN,Force,Richard,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Force,7/14/2020,Complainant Unavailable,NaN,MOUNTED,8300607.0,NaN,NaN,Force,Walter,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Beat,7/14/2020,Unsubstantiated,NaN,MOUNTED,8800504.0,NaN,NaN,Force,Walter,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Vehicle Searched,7/14/2020,Unsubstantiated,NaN,MOUNTED,9201176.0,NaN,NaN,Abuse of Authority,Walter,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Nasty Words,7/14/2020,Unsubstantiated,NaN,MOUNTED,9201176.0,NaN,NaN,Discourtesy,Walter,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2090,NaN,NaN,NaN,2013-10191,BK.NO.TRAFF.ENF.UNIT,NaN,7/31/2013,2/25/2015,NaN,Delora,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2091,NaN,NaN,NaN,2014-11382,MELD,NaN,3/27/2014,2/4/2015,NaN,Enrique,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2092,NaN,NaN,NaN,2012-6973,No. Inter. Ctrl.,NaN,2/16/2012,10/8/2013,NaN,Muhammad,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2093,NaN,NaN,NaN,2012-7731,QNS. TRAFF. ENF. Unit,NaN,8/15/2012,7/23/2013,NaN,Milagros,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2094,NaN,NaN,NaN,84724/08,NO. INTER.. CTRL.,NaN,10/20/2008,6/9/2012,NaN,Wilma,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [136]:
df_discipline = pd.read_csv('New York, NY/From Buzzfeed/nypd-discipline.csv', engine='python')

In [108]:
print(df_discipline.shape)
df_discipline.head()

(2123, 4)

,Case,NameNo,Command,URL
0,2009-1137,CORY BENOWITZ / 9297xx,TD 33,https://www.documentcloud.org/documents/441929...
1,2010-2690,JASON JEREMIAH / 9368xx,TD 33,https://www.documentcloud.org/documents/441929...
2,2011-5497,CHRISTOPHER AITOLA / 9145xx,63 PCT,https://www.documentcloud.org/documents/441929...
3,86365/10,CHRISTOPHER JONES / 9042xx,MELD,https://www.documentcloud.org/documents/441929...
4,2010-3009,LANA WARREN / 3271xx,PERS.ORD.SECT.,https://www.documentcloud.org/documents/441890...

In [156]:
df = pd.merge(df_discipline, df_personnel, on='Case', how='outer')

In [157]:
df['Badge No.'] = df['NameNo'].str.slice(-6)

In [159]:
df['Command']=np.where(df.Command_x.isnull(),df.Command_y,df.Command_x)

In [166]:
df.drop(['NameNo', 'Command_x', 'Command_y'], axis=1, inplace=True)

In [150]:
print(df_discipline.shape, df_personnel.shape)

(2123, 4) (2095, 12)

In [167]:
df

,Case,URL,Source Image,Rank,Tax No.,Investigating Agency,Date of Charges,Date of Disposition,ProperSpecs,ProperPenalty,First Name,Last Name,Badge No.,Command
0,2009-1137,https://www.documentcloud.org/documents/441929...,April-June-2012-335.png,SGT,936814.0,MED. DIV.,7/6/2009,1/17/2012,1. Wrongfully Directed Other Members Of The Se...,Forfeiture Of Five (5) Vacation Days,Cory,Benowitz,9297xx,TD 33
1,2010-2690,https://www.documentcloud.org/documents/441929...,April-June-2012-335.png,SGT,936814.0,MED. DIV.,10/22/2010,1/17/2012,1. Wrongfully Advised The Medical Division Tha...,Forfeiture Of Ten (10) Vacation Days.,Jason,Jeremiah,9368xx,TD 33
2,2011-5497,https://www.documentcloud.org/documents/441929...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9145xx,63 PCT
3,86365/10,https://www.documentcloud.org/documents/441929...,April-June-2012-335.png,DT3,904220.0,IAB,3/22/2010,1/17/2012,1. Wrongfully Possessed A Controlled Substance...,Respondent Was Dismissed From The New York Pol...,Christopher,Jones,9042xx,MELD
4,2010-3009,https://www.documentcloud.org/documents/441890...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3271xx,PERS.ORD.SECT.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2154,201-288,NaN,April-June-2012-455.png,SPAA,326580.0,DET. SQD. MAN.,2/21/2012,4/30/2012,1. Wrongfully Discourteous To A Supervisor. Gu...,Letter Of Reprimand.,Saundrea,Coleman,NaN,DET. BORO. MAN.
2155,2013-+10993,NaN,October-December-2014-244.png,SSA,353821.0,IAB,3/21/2014,5/19/2014,"1. While Off-Duty, Engaged In Conduct Prejudic...",Forfeiture Of Thirty (30) Vacation Days,James,Gonzalez,NaN,60 PCT.SSU
2156,20011-5563,NaN,April-June-2013-206.png,TEA,333262.0,OFF. CHIEF OF TRANSP,3/1/2012,1/2/2013,1. Wrongfully Absent From Assignment Without P...,Forfeiture Of Fifteen (15) Vacation Days.,Sabir,Ali,NaN,TSO INT. RESP/SPEC. EVENTS
2157,20111-4452,NaN,April-June-2012-369.png,TEA,347599.0,IAB,5/23/2011,4/23/2012,1. Excessively Absent On Eleven (11) Occasions...,See Case # 2010-2954 For Penalty,Carlene,Duncan,NaN,BK.N.TRAFF. ENF. UNIT
2158,010-2216,NaN,January-March-2012-128.png,TEA,347624.0,TRB. SO. INT. CTRL.,4/21/2010,10/25/2011,1. Engaged In A Physical Altercation With A Fa...,Forfeiture Of Thirty (30) Days Time On Suspens...,Hector,Rodriguez,NaN,TRB. SO. INT. CTRL.