In [1]:
import pandas as pd

In [2]:
df_ccrb = pd.read_csv('From CCRB via ProPublica/CCRB-Complaint-Data_202007271729/allegations_202007271729.csv')

In [3]:
print(df_ccrb.shape)
df_ccrb.head()

(33358, 27)

,unique_mos_id,first_name,last_name,command_now,shield_no,complaint_id,month_received,year_received,month_closed,year_closed,...,mos_age_incident,complainant_ethnicity,complainant_gender,complainant_age_incident,fado_type,allegation,precinct,contact_reason,outcome_description,board_disposition
0,10004,Jonathan,Ruiz,078 PCT,8409,42835,7,2019,5,2020,...,32,Black,Female,38.0,Abuse of Authority,Failure to provide RTKA card,78.0,Report-domestic dispute,No arrest made or summons issued,Substantiated (Command Lvl Instructions)
1,10007,John,Sears,078 PCT,5952,24601,11,2011,8,2012,...,24,Black,Male,26.0,Discourtesy,Action,67.0,Moving violation,Moving violation summons issued,Substantiated (Charges)
2,10007,John,Sears,078 PCT,5952,24601,11,2011,8,2012,...,24,Black,Male,26.0,Offensive Language,Race,67.0,Moving violation,Moving violation summons issued,Substantiated (Charges)
3,10007,John,Sears,078 PCT,5952,26146,7,2012,9,2013,...,25,Black,Male,45.0,Abuse of Authority,Question,67.0,PD suspected C/V of violation/crime - street,No arrest made or summons issued,Substantiated (Charges)
4,10009,Noemi,Sierra,078 PCT,24058,40253,8,2018,2,2019,...,39,NaN,NaN,16.0,Force,Physical force,67.0,Report-dispute,Arrest - other violation/crime,Substantiated (Command Discipline A)

In [4]:
df_ccrb.columns

Index(['unique_mos_id', 'first_name', 'last_name', 'command_now', 'shield_no',
       'complaint_id', 'month_received', 'year_received', 'month_closed',
       'year_closed', 'command_at_incident', 'rank_abbrev_incident',
       'rank_abbrev_now', 'rank_now', 'rank_incident', 'mos_ethnicity',
       'mos_gender', 'mos_age_incident', 'complainant_ethnicity',
       'complainant_gender', 'complainant_age_incident', 'fado_type',
       'allegation', 'precinct', 'contact_reason', 'outcome_description',
       'board_disposition'],
      dtype='object')

In [5]:
df_ccrb = df_ccrb[['complaint_id', 'rank_abbrev_now', 'first_name', 'last_name', 'command_now', 'command_at_incident' ]]

In [6]:
df_ccrb.rename({'rank_abbrev_now': 'Rank', 'command_now': 'Present Command', 
                'command_at_incident': 'Command at Incident'}, axis=1, inplace=True)
df_ccrb.head()

   complaint_id Rank first_name last_name Present Command Command at Incident
0         42835  POM   Jonathan      Ruiz         078 PCT             078 PCT
1         24601  POM       John     Sears         078 PCT                PBBS
2         24601  POM       John     Sears         078 PCT                PBBS
3         26146  POM       John     Sears         078 PCT                PBBS
4         40253  POF      Noemi    Sierra         078 PCT             078 PCT

In [7]:
df_personnel = pd.read_csv('New York, NY/From a source/NYPD Personnel Orders.csv', engine='python')

In [8]:
print(df_personnel.shape)
df_personnel.head()

(2095, 11)

,Source Image,Case,Rank,Name,Tax No.,Present Command,Command Prefï¿½d Charges,Date of Charges,Date of Disposition,ProperSpecs,ProperPenalty
0,October-December-2013-155.png,2011-4889,ADMIN TEA,PETER MURILLO,331345,BX.TOW.PND.,IAB,9/13/2011,4/24/2013,1.Did Improperly Release A Towed Vehicle That ...,Forfeiture Of Five (5) Days Annual Leave.
1,April-June-2012-304.png,2010-3306,ADMIN. SSM,WILBUR JONES,335663,SSD,IAB,1/3/2011,1/31/2012,1. Improperly Issued A Command Discipline To A...,Forfeiture Of Five (5) Vacation Days.
2,July-September-2012-229.png,2011-5511,AGENCY ATT.,Evan Gluck,350518,LEGAL BUR.,IAB,1/19/2012,6/26/2012,1. Wrongfully Prepared Two (2) Criminal Court ...,Forfeiture Of Thirty (30) Vacation Days.
3,January-March-2012-3.png,2010-86576,AM,RICHARD SAUNDERS,345566,FLEET SERV. DIV.,FLEET SERV. DIV.,3/16/2010,9/15/2011,1. Engaged In A Physical Altercation With A Fa...,Forfeiture Of Thirty (30) Days Time On Suspens...
4,October-December-2013-154.png,2012-7397,ARCH.,Godswill Ogbonnaya,326144,BUILD. MAINT. SECT.,BUILD. MAINT. SECT.,6/4/2012,4/23/2013,1. Failed To Give Notice To The Department Tha...,See Penalty For Case #2010-1928.

In [103]:
df_personnel.rename({'Command Prefï¿½d Charges': 'Command at Incident'}, axis=1, inplace=True)

In [104]:
df_personnel[['first_name','last_name']] = df_personnel['Name'].loc[df_personnel['Name'].str.split().str.len() == 2].str.split(expand=True)

In [105]:
df_personnel.drop('Name', axis=1, inplace=True)
df_personnel['first_name'] = df_personnel['first_name'].str.title()
df_personnel['last_name'] = df_personnel['last_name'].str.title()
df_personnel.head()

,Source Image,Case,Rank,Tax No.,Present Command,Command at Incident,Date of Charges,Date of Disposition,ProperSpecs,ProperPenalty,first_name,last_name
0,October-December-2013-155.png,2011-4889,ADMIN TEA,331345,BX.TOW.PND.,IAB,9/13/2011,4/24/2013,1.Did Improperly Release A Towed Vehicle That ...,Forfeiture Of Five (5) Days Annual Leave.,Peter,Murillo
1,April-June-2012-304.png,2010-3306,ADMIN. SSM,335663,SSD,IAB,1/3/2011,1/31/2012,1. Improperly Issued A Command Discipline To A...,Forfeiture Of Five (5) Vacation Days.,Wilbur,Jones
2,July-September-2012-229.png,2011-5511,AGENCY ATT.,350518,LEGAL BUR.,IAB,1/19/2012,6/26/2012,1. Wrongfully Prepared Two (2) Criminal Court ...,Forfeiture Of Thirty (30) Vacation Days.,Evan,Gluck
3,January-March-2012-3.png,2010-86576,AM,345566,FLEET SERV. DIV.,FLEET SERV. DIV.,3/16/2010,9/15/2011,1. Engaged In A Physical Altercation With A Fa...,Forfeiture Of Thirty (30) Days Time On Suspens...,Richard,Saunders
4,October-December-2013-154.png,2012-7397,ARCH.,326144,BUILD. MAINT. SECT.,BUILD. MAINT. SECT.,6/4/2012,4/23/2013,1. Failed To Give Notice To The Department Tha...,See Penalty For Case #2010-1928.,Godswill,Ogbonnaya

In [106]:
df_personnel['Rank'].value_counts()

PO                 989
SSA                200
SGT                186
TEA                158
DT3                127
                  ...
AM                   1
MV OP.               1
DT 1                 1
ASSOC. TEA SUP.      1
TEA SUP              1
Name: Rank, Length: 90, dtype: int64

In [107]:
df_discipline = pd.read_csv('New York, NY/From Buzzfeed/nypd-discipline.csv', engine='python')

In [108]:
print(df_discipline.shape)
df_discipline.head()

(2123, 4)

,Case,NameNo,Command,URL
0,2009-1137,CORY BENOWITZ / 9297xx,TD 33,https://www.documentcloud.org/documents/441929...
1,2010-2690,JASON JEREMIAH / 9368xx,TD 33,https://www.documentcloud.org/documents/441929...
2,2011-5497,CHRISTOPHER AITOLA / 9145xx,63 PCT,https://www.documentcloud.org/documents/441929...
3,86365/10,CHRISTOPHER JONES / 9042xx,MELD,https://www.documentcloud.org/documents/441929...
4,2010-3009,LANA WARREN / 3271xx,PERS.ORD.SECT.,https://www.documentcloud.org/documents/441890...

In [109]:
df_marshalls = pd.read_excel('New York, NY/City Marshals/MuckRock FOIA/Item_1_-_DOI_FOIL_Response.xlsx')

In [110]:
df_marshalls.head()

,CASE_NUMBER,IGO,ALLEGATION,DISPOSITION,CASE_OPEN_DATE,CASE_CLOSE_DATE
0,14-00117,IGO - MARSHALS BUREAU,EVICTION COMPLAINT,System Closed,06-JAN-14,06-JAN-14
1,14-00127,IGO - MARSHALS BUREAU,SERVICE COMPLAINT,System Closed,06-JAN-14,07-JAN-14
2,14-00127,IGO - MARSHALS BUREAU,SERVICE COMPLAINT,System Closed,06-JAN-14,07-JAN-14
3,14-00145,IGO - MARSHALS BUREAU,INCOME EXECUTION COMPLAINT,System Closed,07-JAN-14,07-JAN-14
4,14-00151,IGO - MARSHALS BUREAU,EVICTION COMPLAINT,System Closed,07-JAN-14,07-JAN-14